name: netflix_clone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  equatable: ^2.0.5
  http: ^1.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  # alan_voice: 3.0.0
  video_player: ^2.8.5
  flick_video_player: ^0.5.0
  youtube_player_flutter: ^9.0.0
  flutter_share: ^2.0.0
  bloc: ^8.1.4 
  flutter_bloc: ^8.1.5
  dio: ^5.4.2+1
  timeago: ^3.3.0
  animate_do: ^3.3.4
  provider: ^6.1.2
  comment_box: ^0.0.18
  flutter_instagram_storyboard: ^0.0.8
  shimmer: ^3.0.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  get: ^4.6.6
  # razorpay_flutter: ^1.3.0
  fluttertoast: ^8.2.4
  razorpay_flutter: ^1.3.0
  youtube_explode_dart: ^2.2.1
  share_plus: ^6.3.4
  # razorpay_flutter: ^1.3.0
  # razorpay_flutter: ^1.3.0
  # provider: ^5.0.0
  # firebase_core: ^2.28.0
  # firebase_auth: ^4.19.0
  # cloud_firestore: ^4.16.0
  # firebase_storage: ^11.7.0
  # phonepe_payment_sdk: ^2.0.1
  # crypto: ^3.0.3
  # razorpay_flutter: ^1.3.6
  # fluttertoast: ^8.2.4
  # lottie: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/netflix-3.png
     - assets/contract.png
     - assets/devices.png
     - assets/download.png
     - assets/logo.png
     - assets/netflix.json
     - assets/welcome/watchEverywhere.jpg
     - assets/welcome/everyFan.jpg
     - assets/welcome/cancelAnytime.jpg
     - assets/welcome/howDoiWatch.heic
     - assets/BottomIcons/newNhot.png
     - assets/BottomIcons/newNhot_light.png
     - assets/BottomIcons/home_light.png
     - assets/BottomIcons/home.png
     - assets/BottomIcons/userProfile.png
     - assets/New&Hot/screencast.png
     - assets/New&Hot/search.png
     - assets/cancel.png
     - assets/ua.jpg
     - assets/play.png
     - assets/a.png
     - assets/likeDark.png
     - assets/likeLight.png
     - assets/share.png
     - assets/done.png
     - assets/plus.png
     - assets/profile/prof1.png
     - assets/profile/prof2.png
     - assets/profile/prof3.png
     - assets/profile/prof4.png
     - assets/profile/prof5.png
     - assets/profile/edit.png
     - assets/profile/notification.png
     - assets/profile/download.png
     - assets/BottomIcons/teaser_light.png
     - assets/BottomIcons/teaser.png
     - assets/loader.json
     - assets/iosLoading.json
     - assets/loading.json
     - assets/accountSplashScreen.json





