// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCjMvngheBnGNDcvPSyIvxgAQHknbDUP4',
    appId: '1:375751433107:web:11126b8ac86f7772886666',
    messagingSenderId: '375751433107',
    projectId: 'flixstreaming-d7054',
    authDomain: 'flixstreaming-d7054.firebaseapp.com',
    storageBucket: 'flixstreaming-d7054.appspot.com',
    measurementId: 'G-55SNRYG9MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDmCEozW_dZAiY6fYvngzfVeJRej4LBw',
    appId: '1:375751433107:android:ad10fca367d575a4886666',
    messagingSenderId: '375751433107',
    projectId: 'flixstreaming-d7054',
    storageBucket: 'flixstreaming-d7054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6j3qPd7-mFbs9yDfA6v_T43XDjlkhvw4',
    appId: '1:375751433107:ios:9b7b1e5dc59d8885886666',
    messagingSenderId: '375751433107',
    projectId: 'flixstreaming-d7054',
    storageBucket: 'flixstreaming-d7054.appspot.com',
    iosBundleId: 'com.example.netlfix12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6j3qPd7-mFbs9yDfA6v_T43XDjlkhvw4',
    appId: '1:375751433107:ios:dd8a7ae2d3e7be10886666',
    messagingSenderId: '375751433107',
    projectId: 'flixstreaming-d7054',
    storageBucket: 'flixstreaming-d7054.appspot.com',
    iosBundleId: 'com.example.netlfix',
  );
}
